# default configuration
baseUrl = "./"
canonifyURLs = false
languageCode = "it"
summaryLength = "10"
theme = "kross-hugo"
title = "DMI Insider"
logo = "images/logo.svg"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "Chi siamo"
weight = 1

[[menu.main]]
URL = "projects"
name = "Progetti"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contatti"
weight = 4


# default parameters
[params]
home = "Home"
logo = "images/logo.svg"
# theme color
theme_color = "#399ff3"
# copyright
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/dmiinsider"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/dmiinsider/"
